import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { CirclePlus } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full pb-10 flex flex-col">
        <div className="sticky top-0 right-0 bg-white z-100 left-0 flex flex-row justify-between align-center p-4 shadow">
          <Link href="/dashboard">
            <Button variant="link">Dashboard</Button>
          </Link>
          <Link href="/expenses">
            <Button variant="link">Expense Tracker</Button>
          </Link>
          <Link href="/expenses/add">
            <Button>
              Create
              <CirclePlus />
            </Button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
